### ISSUE TITLE
error when using this module

### ISSUE THREAD

**Issue by focussing** [humy2833/easy-ftp#9]
...dir.../node_modules/ftp-simple/ftp.js:191
				let newPath = pathUtil.join(path, value.name);
				^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/raymond/stack/sites/squarell-webpack/node_modules/ftp-simple/main.js:2:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-demo@1.0.0 deploy: `node build/deploy.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-demo@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raymond/.npm/_logs/2017-07-07T08_56_38_324Z-debug.log
iMac:squarell-webpack raymond$

**Comment by ezetojo** [comment]
same happens. i fixed it adding "use strict"; on first line of ftp-simple/ftp.js

**Comment by humy2833** [comment]
Sorry.
I did not know the problem because the node.js version was high.
It has been modified.
